services:
  server:
    build: .
    env_file:
      - ./.env
    environment:
      - TZ='Asia/Kolkata'
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - TZ='Asia/Kolkata'
    volumes:
      - mongo-db:/data/db
  
  redis:
    image: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: 
      - /bin/sh
      - -c
      - redis-server --requirepass "${REDIS_PASSWORD}"
    environment:
      - TZ='Asia/Kolkata'
    volumes:
      - redis-db:/data

volumes:
  mongo-db:

  redis-db:
