services:
  server:
    build: .
    env_file:
      - ./.env
    environment:
      - TZ='Asia/Kolkata'
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongo
      - redis
      - libretranslate

  mongo:
    image: mongo
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - TZ='Asia/Kolkata'
    volumes:
      - mongo-db:/data/db
  
  redis:
    image: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: 
      - /bin/sh
      - -c
      - redis-server --requirepass "${REDIS_PASSWORD}"
    environment:
      - TZ='Asia/Kolkata'
    volumes:
      - redis-db:/data

  libretranslate:
    image: libretranslate/libretranslate
    container_name: libretranslate
    ports:
      - "5000:5000"  # Exposes LibreTranslate API on port 5000
    restart: unless-stopped
    tty: true
    environment:
      - LT_FRONTEND_LANGUAGE_TARGET=en
      - LT_LOAD_ONLY=en,hi,bn  # Pass the languages to load as an environment variable


networks:
  default:
    name: bharatfd-faq

volumes:
  mongo-db:

  redis-db:
  # libretranslate_models:
